#!/usr/bin/env bash
# Moves all files in an existing repository into a new subfolder
move_files_into_subfolder() {
  local subfolder="$1"
  local -a files=( $(ls -a) )
  for file in ${files[@]}
  do
    if [[ "$file" != "wpmusite.dev" && "$file" != ".git" && "$file" != "mv${subfolder}" && "$file" != ".." && "$file" != "." ]]; then
      git mv $file ./wpmusite.dev/${subfolder}
    fi
  done
}
echo "----->Ensure devbedrock is checked out..."
git checkout devbedrock
\rm -rf wpmusite.dev && \mkdir -p wpmusite.dev/bedrock
echo "----->Merging upbedrock into devbedrock ..."
git merge --no-edit --squash upbedrock --allow-unrelated-histories
move_files_into_subfolder bedrock
\mv wpmusite.dev/bedrock wpmusite.dev/site
git add -A
git commit -m "devbedrock: merged upbedrock code into subfolder @ $(date)"
