#!/usr/bin/env bash
git checkout upstream
if !(git remote | grep -iq upstream); then
    git remote add upstream https://github.com/roots/trellis 2>/dev/null
    git remote set-url --push upstream fetchonly 2>/dev/null
fi
git pull --force upstream master
