#!/usr/bin/env bash
echo "----->Ensure devbase is checked out..."
git checkout devproj
echo "----->Merging devtrellis into devproj ..."
git merge --no-edit devtrellis --allow-unrelated-histories
read -n1 -rsp $'Press any key to continue or Ctrl+C to exit...\n'
echo "----->Merging devbedrock into devproj ..."
git merge --no-edit devbedrock --allow-unrelated-histories
