#!/usr/bin/env bash
git checkout uptrellis
if !(git remote | grep -iq uptrellis); then
    git remote add uptrellis https://github.com/roots/trellis 2>/dev/null
    git remote set-url --push uptrellis fetchonly 2>/dev/null
fi
git pull --force uptrellis master
