<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */

// Define global PATH constants here manually
define('_ROOT_DIR_', dirname(__DIR__));
define('_WEBROOT_DIR_', __DIR__);
// Load custom pre-bootstrap modifications
require_once(_ROOT_DIR_ . '/mods/preconf.php');
// Load vendor modules
require_once(_ROOT_DIR_ . '/vendor/autoload.php');
// Load wp application configs where the .env is loaded.
require_once(_ROOT_DIR_ . '/config/application.php');
// Load custom post-bootstrap modifications
require_once(_ROOT_DIR_ . '/mods/postconf.php');

/**
 * Bootstrap WordPress
 */
require_once(ABSPATH . 'wp-settings.php');
