wordpress_env_defaults:
  wp_env: "{{ env }}"
  wp_allow_multisite: true
  root_domain: "{{ site_hosts_canonical | first }}"
  wp_proto: "{{ ssl_enabled | ternary('https', 'http') }}"
  wp_home: "{{ ssl_enabled | ternary('https', 'http') }}://{{ site_hosts_canonical | first }}"
  db_host: localhost
  db_port: 3306
  db_name: "{{ item.key | underscore }}_{{ env[0:2] }}"
  db_user: "{{ item.key | underscore }}"
  db_charset: "utf8mb4"
  db_collate: "utf8mb4_unicode_ci"
  disable_wp_cron: true

site_env: "{{ wordpress_env_defaults | combine(item.value.env | default({}), vault_wordpress_sites[item.key].env) }}"
site_hosts_canonical: "{{ item.value.site_hosts | map(attribute='canonical') | list }}"
site_hosts_redirects: "{{ item.value.site_hosts | selectattr('redirects', 'defined') | sum(attribute='redirects', start=[]) | list }}"
site_hosts: "{{ site_hosts_canonical | union(site_hosts_redirects) }}"
ssl_enabled: "{{ item.value.ssl is defined and item.value.ssl.enabled | default(false) }}"
